# Generated by Django 5.1.2 on 2025-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
