# Generated by Django 5.2 on 2025-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pizza_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pix_qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('pix', 'PIX')], max_length=20),
        ),
    ]
