# Generated by Django 5.2 on 2025-04-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payment_pix_qr_code_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
