# Generated by Django 5.1.2 on 2025-04-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('pix', 'PIX'), ('mercadopago', 'Mercado Pago')], max_length=20),
        ),
    ]
