name: Build and deploy Python app to Azure Web App - es2back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./backend/back # Changed to point to inner back folder
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn  # Explicitly install gunicorn

      - name: Create deployment package
        working-directory: ./backend/back
        run: |
          # Create a proper Azure deployment structure
          mkdir -p deployment/backend/back
          cp -r * deployment/backend/back/
          cd deployment
          zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          mkdir -p deployment
          unzip release.zip -d deployment
          # Azure expects files in /home/site/wwwroot
          mv deployment/backend/back/* deployment/
          rm -rf deployment/backend
          zip -r final_release.zip deployment/*

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "es2back"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F331B359598E4940A3E4F3E152E3C4F8 }}
          package: final_release.zip
