name: Build and deploy Python app to Azure Web App - es2back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./backend/back
        run: |
          python -m venv venv
          source venv/bin/activate
          # Install from both possible requirements.txt locations
          if [ -f "../requirements.txt" ]; then
            pip install -r ../requirements.txt
          fi
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          pip install gunicorn

      - name: Create deployment package
        working-directory: ./backend/back
        run: |
          # Clean approach without recursive copying
          mkdir -p _deploy
          # Copy all files except venv and deployment dirs
          find . -maxdepth 1 ! -name '.' ! -name 'venv' ! -name '_deploy' -exec cp -r {} _deploy/ \;
          # Include requirements.txt if it exists
          if [ -f "../requirements.txt" ]; then
            cp ../requirements.txt _deploy/
          fi
          cd _deploy
          zip -r ../release.zip .
          cd ..
          rm -rf _deploy

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ./backend/back/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "es2back"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F331B359598E4940A3E4F3E152E3C4F8 }}
          package: release.zip
